import { makeGlossaryMatcher } from '../../glossary.js'

// Glossaire de la catégorie Python pour la data, en langage simple (débutant).
// Une définition ne s'affiche QUE si son terme apparaît (mot entier) dans la
// question ou les choix d'un quiz.
export const GLOSSARY = [
  // --- numpy ---
  { term: 'ndarray', aliases: ['ndarray', 'tableau numpy', 'np.array'], def: "Le tableau de numpy : toutes les cases ont le même type, la taille est fixe, et les opérations (+, *, >, np.exp…) s'appliquent case par case sans boucle. Un vecteur est 1D, une matrice 2D." },
  { term: 'shape', aliases: ['shape', 'forme'], def: "La forme d'un tableau, un tuple : (3,) pour un vecteur de 3 cases, (4, 3) pour 4 lignes et 3 colonnes. Neuf bugs sur dix en data viennent de formes qui ne correspondent pas." },
  { term: 'dtype', aliases: ['dtype', 'float64', 'int64'], def: "Le type des valeurs d'un tableau numpy : int64 (entiers), float64 (décimaux), bool. Un tableau d'entiers ne peut pas stocker de décimales, d'où le réflexe d'écrire 3.0 plutôt que 3." },
  { term: 'Slicing', aliases: ['slicing', 'tranche', 'slice'], def: "Découper un tableau avec v[début:fin:pas], fin exclue : v[:6] les six premières, v[1:] sauf le premier, v[:-1] sauf le dernier, v[1::2] les indices impairs. Une tranche est une vue, pas une copie." },
  { term: 'Vectorisation', aliases: ['vectorisation', 'vectorisé', 'vectorisée', 'broadcasting'], def: "Appliquer une opération à tout un tableau d'un coup (v1 + v2, v ** 2, v > 0) au lieu d'écrire une boucle for. La boucle existe, mais en C dans numpy : cent fois plus rapide." },
  { term: 'Masque booléen', aliases: ['masque', 'masques', 'masque booléen', 'index booléen', 'mask'], def: "Un tableau de True/False obtenu par une condition (v > 0). v[masque] garde les cases True, v[masque] = 0 les modifie, np.mean(masque) donne la proportion de True (une probabilité estimée). & | ~ pour ET, OU, NON." },
  { term: 'Vue / copie', aliases: ['vue', 'copie', 'view', 'copy'], def: "Une tranche v[0:2] est une vue : elle regarde la même mémoire que v, donc la modifier modifie v. Un masque booléen renvoie une copie indépendante. .copy() force une copie." },
  { term: 'axis', aliases: ['axis', 'axe'], def: "Le paramètre des fonctions d'agrégation (mean, sum, max…) qui dit quel axe on écrase : axis=0 donne une valeur par colonne, axis=1 une valeur par ligne, sans axis une seule valeur." },
  { term: 'reshape', aliases: ['reshape'], def: "Changer la forme d'un tableau sans changer ses valeurs, à nombre de cases constant : (10, 10) → (20, 5). −1 laisse numpy déduire une dimension ; x.reshape(-1, 1) fait une colonne (n, 1), le format attendu par scikit-learn." },
  { term: 'stack / concatenate', aliases: ['stack', 'concatenate', 'np.stack', 'np.concatenate'], def: "np.stack empile en créant une dimension en plus (deux vecteurs (10,) → (2, 10) ; axis=-1 met la nouvelle dimension en dernier). np.concatenate colle bout à bout sur une dimension existante ((10,) + (10,) → (20,))." },
  { term: 'argmax / argmin', aliases: ['argmax', 'argmin', 'np.argmax'], def: "L'indice (la position) du maximum ou du minimum d'un tableau, pas sa valeur. np.argmax(Q) est « le meilleur choix connu » dans epsilon-greedy." },
  { term: 'np.where', aliases: ['np.where', 'where'], def: "np.where(condition, a, b) : a là où la condition est vraie, b ailleurs, case par case. Sert à choisir sans boucle, par exemple tirer un test avec une probabilité différente selon que la personne est malade ou non." },
  { term: 'np.clip', aliases: ['np.clip', 'clip'], def: "Borne un tableau entre un minimum et un maximum : np.clip(v, None, t) ramène à t tout ce qui dépasse t ; np.clip(p, 1e-7, 1 − 1e-7) évite log(0) dans la BCE." },
  { term: 'Produit matriciel (@)', aliases: ['@', 'produit matriciel', 'np.dot', 'dot'], def: "w @ x est le produit scalaire Σ wi·xi ; X @ w calcule toutes les prédictions d'une régression linéaire d'un coup quand X a une colonne de 1 devant (l'astuce x0 = 1)." },
  // --- pandas / matplotlib ---
  { term: 'DataFrame', aliases: ['dataframe', 'df'], def: "Le tableau de pandas : des colonnes nommées (size, price…), un index, des types mélangés possibles. Obtenu par pd.read_csv, exploré avec head, shape, describe." },
  { term: 'Series', aliases: ['series'], def: "Une colonne d'un DataFrame : un vecteur numpy avec un nom et un index. df['price'] est une Series, df[['price']] un DataFrame à une colonne." },
  { term: 'read_csv', aliases: ['read_csv', 'pd.read_csv', 'csv'], def: "pd.read_csv('fichier.csv') charge un fichier CSV (ou une URL, ou un fichier envoyé par st.file_uploader) dans un DataFrame." },
  { term: 'describe', aliases: ['describe', 'df.describe'], def: "df.describe() donne pour chaque colonne numérique le nombre de valeurs, la moyenne, l'écart-type, le min, les quartiles et le max : les statistiques descriptives en une ligne." },
  { term: 'groupby', aliases: ['groupby'], def: "df.groupby('col')['autre'].mean() découpe les lignes en groupes (une valeur de col chacun) puis agrège chaque groupe : le prix moyen par nombre de pièces, par exemple." },
  { term: 'to_numpy', aliases: ['to_numpy', '.values'], def: "df[['a', 'b']].to_numpy() rend le tableau numpy sous-jacent : la matrice X (n exemples, p features) qu'attend un modèle. df['y'].to_numpy() donne le vecteur y." },
  { term: 'NaN (valeur manquante)', aliases: ['nan', 'valeur manquante', 'valeurs manquantes', 'isna', 'dropna', 'fillna'], def: "Une case vide dans les données. df.isna().sum() les compte par colonne, dropna() supprime les lignes incomplètes, fillna(valeur) les remplace. Un modèle numpy plante sur un NaN." },
  { term: 'Figure / axes', aliases: ['figure', 'axes', 'plt.subplots', 'subplots'], def: "fig, ax = plt.subplots() crée la feuille (figure) et le graphique dessus (axes). On dessine avec ax.scatter, ax.plot, ax.hist, et on passe fig à st.pyplot dans Streamlit." },
  { term: 'scatter', aliases: ['scatter', 'nuage de points'], def: "ax.scatter(x, y) : un nuage de points, un point par exemple. Le premier graphique à faire avant tout modèle, pour voir si la relation est linéaire et repérer les points aberrants." },
  // --- Streamlit ---
  { term: 'Streamlit', aliases: ['streamlit'], def: "Librairie qui transforme un script Python en application web : widgets, tableaux, graphiques, sans HTML ni JavaScript. Lancée avec streamlit run app.py sur localhost:8501." },
  { term: 'Widget', aliases: ['widget', 'widgets', 'st.text_input', 'st.slider', 'st.button'], def: "Un élément d'interaction Streamlit (text_input, slider, button, selectbox, file_uploader…) qui renvoie directement sa valeur : name = st.text_input('Prénom')." },
  { term: 'Script rejoué (rerun)', aliases: ['rerun', 'relancé', 'relance', 'ré-exécuté', 'rejoué'], def: "À chaque interaction, Streamlit ré-exécute tout le script du haut en bas. D'où deux conséquences : le coûteux est refait (remède : cache_data) et les variables repartent de zéro (remède : session_state)." },
  { term: 'st.cache_data', aliases: ['cache_data', 'st.cache_data', 'cache', 'st.cache', 'cache_resource'], def: "Décorateur qui mémorise le résultat d'une fonction par arguments : premier appel exécuté, appels suivants avec les mêmes arguments renvoyés sans exécuter. Pour les données ; cache_resource pour les connexions et modèles." },
  { term: 'st.session_state', aliases: ['session_state', 'st.session_state'], def: "Dictionnaire qui survit aux relances du script pendant la session : compteur, page courante, choix de l'utilisateur. À initialiser avec if 'clé' not in st.session_state." },
  { term: 'sidebar', aliases: ['sidebar', 'st.sidebar', 'barre latérale', 'panneau latéral'], def: "Le panneau latéral gauche : st.sidebar.button(...) ou with st.sidebar:. Sert typiquement à la navigation entre pages avec session_state, ou aux réglages." },
  { term: 'st.map', aliases: ['st.map', 'map'], def: "Affiche un point par ligne d'un DataFrame sur un fond de carte, à partir des colonnes lat et lon (ou latitude / longitude)." },
  // --- Python ---
  { term: 'def / return', aliases: ['def', 'return', 'fonction python'], def: "def nom(paramètres): définit une fonction, son corps est indenté, return renvoie la valeur. Une fonction est un objet : on peut la ranger dans une variable et la passer en paramètre." },
  { term: 'lambda', aliases: ['lambda'], def: "Une fonction anonyme en une ligne : lambda x: 2 * (x - 2). Pratique pour passer une dérivée ou un gradient en paramètre sans écrire un def." },
  { term: 'range', aliases: ['range'], def: "range(n) produit 0, 1, …, n − 1 : n tours de boucle. for _ in range(n) répète n fois sans utiliser le compteur." },
  { term: 'break', aliases: ['break', 'continue'], def: "break sort immédiatement de la boucle (par exemple quand le gradient est assez petit). continue saute à l'itération suivante." },
  { term: 'f-string', aliases: ['f-string', 'fstring'], def: "f'lr = {lr}' insère la valeur d'une variable dans un texte ; f'{x:.4f}' l'arrondit à 4 décimales." },
  { term: 'self / classe', aliases: ['self', 'classe', 'class', '__init__', 'méthode'], def: "class définit un type d'objet ; __init__ est le constructeur ; self est l'objet lui-même dans ses méthodes, et self.w un attribut qu'il porte. model.fit(X, y) appelle fit(model, X, y)." },
  { term: 'pip', aliases: ['pip', 'pip install', 'venv', 'environnement virtuel'], def: "pip install numpy installe une librairie. Un environnement virtuel (python -m venv .venv) isole les librairies d'un projet et leurs versions." },
  { term: 'Notebook', aliases: ['notebook', 'jupyter', 'colab', 'cellule', 'cellules'], def: "Un document de cellules de code exécutées une à une, résultats affichés dessous (Jupyter en local, Google Colab dans le navigateur). Idéal pour explorer ; attention à l'ordre d'exécution des cellules." },
  // --- ML en Python ---
  { term: 'scikit-learn', aliases: ['scikit-learn', 'sklearn'], def: "La librairie du machine learning classique : LinearRegression, LogisticRegression, train_test_split… Tous les modèles s'utilisent pareil : fit, predict. Les attributs appris finissent par un underscore (coef_, intercept_)." },
  { term: 'train_test_split', aliases: ['train_test_split'], def: "Sépare X et y en entraînement et test au hasard : X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0). fit sur train, mesure sur test." },
  { term: 'intercept_ / coef_', aliases: ['intercept_', 'coef_'], def: "Après un fit scikit-learn, intercept_ est le biais w0 et coef_ le tableau des pentes (w1, …). L'underscore final signale un attribut appris." },
  { term: 'Courbe de loss', aliases: ['courbe de loss', 'losses', 'loss'], def: "La MSE (ou BCE) tracée à chaque itération de l'entraînement. Elle doit descendre puis s'aplatir ; si elle remonte ou zigzague, le learning rate est trop grand." },
  { term: 'Normaliser', aliases: ['normaliser', 'normalisation', 'standardiser'], def: "Ramener une feature à moyenne 0 et écart-type 1 : (X − X.mean()) / X.std(), avec les statistiques du jeu d'entraînement seulement. Sans ça, la descente de gradient zigzague quand les échelles diffèrent." },
  { term: 'Générateur (rng) et graine', aliases: ['rng', 'graine', 'seed', 'default_rng', 'np.random'], def: "rng = np.random.default_rng(0) : un générateur de nombres aléatoires avec une graine, pour obtenir les mêmes tirages à chaque exécution. rng.integers, rng.random, rng.normal, rng.choice, rng.permutation." },
  { term: 'Loi des grands nombres', aliases: ['loi des grands nombres', 'moyenne courante', 'cumsum'], def: "La moyenne de n tirages converge vers l'espérance quand n grandit : np.mean(lancers) → 3,5. np.cumsum(lancers) / np.arange(1, n + 1) trace la moyenne courante qui se stabilise." },
  { term: 'Sigmoïde (numpy)', aliases: ['sigmoid', 'sigmoïde', 'np.exp'], def: "1 / (1 + np.exp(−z)), vectorisée : écrase n'importe quel nombre entre 0 et 1. Classe prédite : (p > 0.5).astype(int)." },
  { term: 'BCE (numpy)', aliases: ['bce', 'log loss', 'entropie croisée binaire'], def: "−np.mean(y · np.log(p) + (1 − y) · np.log(1 − p)), avec np.clip(p, 1e-7, 1 − 1e-7) avant pour éviter log(0). Vaut 0 quand on a raison avec confiance, explose quand on a tort avec confiance." },
  { term: 'Epsilon-greedy', aliases: ['epsilon-greedy', 'epsilon greedy', 'eps', 'exploration', 'exploitation'], def: "À chaque tour : avec probabilité ε, un choix au hasard (rng.integers(k), exploration) ; sinon le meilleur connu (np.argmax(Q), exploitation). Q mis à jour par moyenne incrémentale Q[a] += (r − Q[a]) / N[a]." },
]

export const matchGlossary = makeGlossaryMatcher(GLOSSARY)
