import { makeGlossaryMatcher } from '../../glossary.js'

// Glossaire de la catégorie Data science, en langage simple (débutant).
// Une définition ne s'affiche QUE si son terme apparaît (mot entier) dans la
// question ou les choix d'un quiz. Volontairement resserré aux termes qui comptent.
export const GLOSSARY = [
  // --- Données ---
  { term: 'Donnée', aliases: ['donnée', 'données', 'data'], def: "Une information stockée à propos d'un phénomène : une température relevée, un prix de vente, les clics d'un joueur. Sans stockage, ce n'est pas une donnée." },
  { term: 'Dataset', aliases: ['dataset', 'jeu de données'], def: "L'ensemble des exemples dont on dispose pour entraîner et tester un modèle. En supervisé : une matrice X (les entrées) et un vecteur y (les réponses attendues)." },
  { term: 'Feature', aliases: ['feature', 'features', 'variable d’entrée', 'variables d’entrée'], def: "Une variable d'entrée qu'on donne au modèle : la surface d'une maison, son nombre de pièces, la présence d'un jardin. Une colonne de X." },
  { term: 'Label', aliases: ['label', 'labels', 'étiquette', 'étiquettes'], def: "La bonne réponse associée à un exemple, celle que le modèle doit apprendre à retrouver : le prix réel de la maison, « hamster » ou « octodon ». Le vecteur y." },
  // --- ML ---
  { term: 'Modèle', aliases: ['modèle', 'modèles', 'model'], def: "Une fonction mathématique à boutons (les paramètres) qui transforme une entrée x en prédiction. Avant entraînement c'est une famille de fonctions possibles ; après, une seule, les boutons étant réglés." },
  { term: 'Paramètres (poids)', aliases: ['paramètre', 'paramètres', 'poids', 'weights', 'weight'], def: "Les nombres réglables du modèle, notés w ou θ. Entraîner un modèle, c'est trouver les bonnes valeurs de ces nombres. Une régression linéaire à 3 features a 4 poids : w0, w1, w2, w3." },
  { term: 'Loss (fonction d’erreur)', aliases: ['loss', 'fonction d’erreur', "fonction d'erreur", 'fonction de coût'], def: "Un nombre qui mesure à quel point les prédictions sont loin des valeurs attendues. Petit = bon modèle. L'entraînement cherche les poids qui rendent ce nombre le plus petit possible." },
  { term: 'MSE', aliases: ['mse', 'mean squared error', 'erreur quadratique moyenne'], def: "Mean Squared Error : pour chaque exemple on prend (prédiction − attendu)², puis on fait la moyenne. C'est la loss standard de la régression." },
  { term: 'BCE (entropie croisée binaire)', aliases: ['bce', 'binary cross-entropy', 'entropie croisée binaire', 'log loss'], def: "La loss de la classification binaire : −(1/m) Σ [y·log ŷ + (1 − y)·log(1 − ŷ)]. Vaut 0 quand on a raison avec confiance, tend vers +∞ quand on a tort avec confiance." },
  { term: 'Cross-entropy', aliases: ['cross-entropy', 'cross entropy', 'entropie croisée'], def: "La loss de la classification à plusieurs classes : elle compare la probabilité prédite pour chaque classe à la vraie classe. La BCE en est le cas à deux classes." },
  { term: 'Prédiction (ŷ)', aliases: ['prédiction', 'prédictions', 'ŷ', 'y_pred'], def: "La sortie du modèle pour une entrée donnée, notée ŷ (« y chapeau »). On la compare à y, la vraie valeur, pour mesurer l'erreur." },
  { term: 'Supervisé', aliases: ['supervisé', 'supervisée', 'supervised'], def: "Apprentissage où chaque exemple vient avec sa bonne réponse (le label y). Le modèle apprend à reproduire la relation entrée → réponse. Régression et classification sont supervisées." },
  { term: 'Non supervisé', aliases: ['non supervisé', 'non supervisée', 'unsupervised'], def: "Apprentissage sans labels : on n'a que les entrées X. Le modèle cherche une structure tout seul, par exemple des groupes (clusters) de points qui se ressemblent." },
  { term: 'Régression', aliases: ['régression', 'regression'], def: "Prédire une valeur numérique continue : un prix, une durée, une température. À ne pas confondre avec la classification, qui prédit une catégorie." },
  { term: 'Classification', aliases: ['classification', 'classifier', 'classer'], def: "Prédire une catégorie parmi un nombre fini de choix : malade ou pas, hamster ou octodon, va acheter ou non." },
  { term: 'Overfitting', aliases: ['overfitting', 'sur-apprentissage', 'surapprentissage', 'par cœur'], def: "Apprentissage par cœur : le modèle est excellent sur les données d'entraînement mais mauvais sur des données nouvelles. On le détecte grâce au jeu de test." },
  { term: 'Capacité', aliases: ['capacité'], def: "La puissance d'expression d'un modèle : le nombre de formes différentes qu'il peut prendre, qui croît avec le nombre de paramètres. Grande capacité = grand risque de sur-apprentissage." },
  { term: 'Régularisation', aliases: ['régularisation', 'regularisation', 'regularization', 'ridge', 'L2'], def: "Ajouter à la loss une pénalité sur la taille des poids (par exemple λ·Σ wi²) pour empêcher le modèle d'apprendre par cœur. λ règle la force de la contrainte." },
  { term: 'Jeu de test', aliases: ['jeu de test', 'test set', 'données de test'], def: "Une partie des données mise de côté, jamais utilisée pour l'entraînement, qui sert à mesurer si le modèle marche sur des exemples qu'il n'a jamais vus." },
  { term: 'Sigmoïde', aliases: ['sigmoïde', 'sigmoid'], def: "La fonction 1 / (1 + exp(−x)). Elle écrase n'importe quel nombre entre 0 et 1, ce qui permet de lire la sortie comme une probabilité. Cœur de la régression logistique." },
  // --- Maths ---
  { term: 'Dérivée', aliases: ['dérivée', 'dérivées', 'dériver'], def: "La pente d'une fonction en un point : de combien f(x) change quand x augmente d'un tout petit peu. Positive = ça monte, négative = ça descend, nulle = plat (souvent un minimum ou un maximum)." },
  { term: 'Dérivée partielle', aliases: ['dérivée partielle', 'dérivées partielles', '∂'], def: "Pour une fonction à plusieurs variables : la dérivée par rapport à UNE variable, en faisant comme si les autres étaient des constantes. Notée ∂f/∂x." },
  { term: 'Gradient', aliases: ['gradient', 'gradients', '∇'], def: "Le vecteur qui rassemble toutes les dérivées partielles d'une fonction. Il pointe dans la direction où la fonction monte le plus vite ; on va dans le sens opposé pour descendre." },
  { term: 'Différentiation automatique', aliases: ['différentiation automatique', 'autodiff', 'autograd'], def: "Un algorithme qui, à partir du code d'un calcul, produit sa valeur et ses dérivées exactes par rapport à chaque entrée, en appliquant la règle de la chaîne sur un graphe d'opérations. C'est ce que font PyTorch et TensorFlow." },
  { term: 'Descente de gradient', aliases: ['descente de gradient', 'gradient descent'], def: "L'algorithme qui minimise une fonction pas à pas : à chaque itération, x ← x − α · f′(x). On avance dans le sens opposé à la pente, avec un pas réglé par α." },
  { term: 'Argmin', aliases: ['argmin', 'arg min'], def: "L'entrée (le x, ou les poids) pour laquelle une fonction atteint son minimum. Le minimum est la valeur la plus basse ; l'argmin est l'endroit où elle est atteinte. En ML on cherche l'argmin de la loss : les poids." },
  { term: 'Boîte noire', aliases: ['boîte noire', 'boite noire', 'black box'], def: "Une fonction dont on ne connaît pas la formule : on ne peut qu'observer ses sorties. Impossible de la dériver, donc pas de descente de gradient ; on tâtonne (essais, grille, hasard)." },
  { term: 'Learning rate (α)', aliases: ['learning rate', 'alpha', 'α', 'taux d’apprentissage', 'pas'], def: "Le coefficient α qui règle la taille de chaque pas de la descente de gradient. Trop petit : on avance lentement. Trop grand : on saute par-dessus le minimum et ça peut diverger." },
  { term: 'Itération', aliases: ['itération', 'itérations', 'iteration'], def: "Un tour de boucle de l'algorithme : calculer le gradient, mettre à jour les poids, recommencer. L'entraînement en enchaîne des centaines ou des milliers." },
  { term: 'Convergence', aliases: ['convergence', 'converger', 'converge'], def: "Quand les itérations se rapprochent de plus en plus d'une valeur stable, sans plus bouger : l'algorithme a trouvé (ou approché) le minimum." },
  { term: 'Produit scalaire', aliases: ['produit scalaire', 'dot product'], def: "Somme des produits terme à terme de deux vecteurs : w·x = w0·x0 + w1·x1 + … Avec x0 = 1, c'est exactement la formule de la régression linéaire." },
  { term: 'Vecteur', aliases: ['vecteur', 'vecteurs', 'vector'], def: "Une liste ordonnée de nombres, par exemple les poids (w0, w1, w2) ou les features d'un exemple. Une matrice est un tableau de vecteurs empilés." },
  { term: 'Logarithme', aliases: ['logarithme', 'log', 'log(x)', 'népérien'], def: "log(x), le logarithme népérien : log(1) = 0, log(x) est négatif entre 0 et 1 et plonge vers −∞ quand x tend vers 0. Sa dérivée est 1/x. Il apparaît dans la BCE et dans le maximum de vraisemblance." },
  // --- Probabilités ---
  { term: 'Indépendants', aliases: ['indépendants', 'indépendantes', 'indépendance', 'indépendant'], def: "Deux événements sont indépendants quand savoir que l'un est arrivé ne change pas la probabilité de l'autre. Alors P(A et B) = P(A)·P(B). Pile puis pile, par exemple." },
  { term: 'Incompatibles', aliases: ['incompatibles', 'incompatible', 'disjoints'], def: "Deux événements qui ne peuvent pas arriver en même temps : P(A et B) = 0. Pile et face au même lancer. À ne pas confondre avec indépendants." },
  { term: 'Probabilité conditionnelle', aliases: ['probabilité conditionnelle', 'sachant que', 'sachant', 'P(A|B)'], def: "P(A|B) : la probabilité de A une fois qu'on sait que B est arrivé. Formule du ET : P(A et B) = P(A)·P(B|A) = P(B)·P(A|B)." },
  { term: 'Formule de Bayes', aliases: ['bayes', 'formule de bayes', 'théorème de bayes', 'bayésien', 'bayésienne'], def: "P(A|B) = P(B|A)·P(A) / P(B). Elle met à jour une croyance (le prior P(A)) avec une observation B pour obtenir le posterior P(A|B). P(B|A) s'appelle la vraisemblance." },
  { term: 'Prior / posterior', aliases: ['prior', 'posterior', 'a priori', 'a posteriori'], def: "Le prior est la probabilité qu'on attribue à une hypothèse avant d'observer les données ; le posterior, celle qu'on lui attribue après. La formule de Bayes fait passer de l'un à l'autre." },
  { term: 'Vraisemblance', aliases: ['vraisemblance', 'likelihood'], def: "La probabilité d'observer les données si une hypothèse (ou des paramètres) est vraie : P(données | hypothèse). Le maximum de vraisemblance choisit les paramètres qui la rendent la plus grande." },
  { term: 'Maximum de vraisemblance', aliases: ['maximum de vraisemblance', 'maximum likelihood'], def: "Méthode pour estimer les paramètres d'une loi à partir de données : on choisit les paramètres qui rendent les données observées les plus probables. Pour une loi normale : la moyenne et l'écart-type empiriques." },
  { term: 'Variable aléatoire', aliases: ['variable aléatoire', 'variables aléatoires'], def: "Un nombre qui dépend du résultat d'une expérience aléatoire : le résultat d'un dé, une taille tirée au hasard. Sa loi donne la probabilité de chaque valeur (discret) ou une densité (continu)." },
  { term: 'Densité de probabilité', aliases: ['densité', 'densité de probabilité'], def: "Pour une variable continue, la courbe p(x) dont l'aire entre a et b donne P(a < X < b). L'aire totale vaut 1 ; la probabilité d'une valeur exacte est nulle." },
  { term: 'Espérance', aliases: ['espérance', 'E[X]', 'expected value'], def: "La moyenne des valeurs possibles d'une variable aléatoire, pondérée par leurs probabilités : E[X] = Σ x·P(X = x). Pour un dé équilibré, 3,5." },
  { term: 'Epsilon-greedy', aliases: ['epsilon-greedy', 'epsilon greedy', 'ε-greedy', 'exploration', 'exploiter', 'explorer'], def: "Stratégie qui arbitre entre exploiter (prendre le meilleur choix connu, probabilité 1 − ε) et explorer (essayer au hasard, probabilité ε). On diminue ε avec le temps." },
]

export const matchGlossary = makeGlossaryMatcher(GLOSSARY)
